export const sportExpertiseMap = {
  Archery: [
    'Focus & Precision',
    'Bow Handling',
    'Posture',
    'Wind Adjustment',
    'Release Timing',
    'Adaptive Grip Techniques (Para)',
    'Visual Target Assistance (Para)',
  ],
  Athletics: [
    'Sprinting Mechanics',
    'Long Distance Stamina',
    'Hurdle Techniques',
    'Relay Baton Passing',
    'Starting Block Techniques',
    'Prosthetic Running Optimization (Para)',
    'Wheelchair Sprint Tuning (Para)',
  ],
  Badminton: [
    'Footwork',
    'Smash Technique',
    'Reflex Drills',
    'Drop Shot Accuracy',
    'Net Play Finesse',
    'Seated Movement Training (Para)',
    'Lightweight Racket Handling (Para)',
  ],
  Basketball: [
    'Shooting Accuracy',
    'Dribbling & Handling',
    'Defensive Strategy',
    'Pick and Roll Execution',
    'Fast Break Decision-Making',
    'Wheelchair Dribbling (Para)',
    'Court Navigation in Chairs (Para)',
  ],
  Boxing: [
    'Punch Combinations',
    'Defense Tactics',
    'Foot Movement',
    'Feinting Techniques',
    'Counterpunch Strategy',
    'One-arm Guard Strategy (Para)',
    'Hearing Cue Reaction Drills (Para)',
  ],
  Cricket: [
    'Batting',
    'Bowling',
    'Wicket Keeping',
    'Fielding',
    'Spin Control',
    'Underarm Bowling Techniques (Para)',
    'Batting with Modified Grips (Para)',
  ],
  Cycling: [
    'Endurance Training',
    'Pace Strategy',
    'Bike Handling',
    'Climbing & Descent Control',
    'Saddle Positioning',
    'Handcycle Racing Tactics (Para)',
    'Visual Cues Synchronization (Para)',
  ],
  Football: [
    'Midfield Control',
    'Goalkeeping',
    'Defensive Tactics',
    'Attacking Plays',
    'Crossing Accuracy',
    'Blindfold Coordination Drills (Para)',
    'Guide Runner Sync (Para)',
  ],
  Gymnastics: [
    'Flexibility Drills',
    'Balance & Beam',
    'Floor Routines',
    'Vault Approaches',
    'Parallel Bars Strength',
    'Upper Body Routine Optimization (Para)',
    'Adaptive Equipment Use (Para)',
  ],
  Hockey: [
    'Stick Handling',
    'Goalkeeping',
    'Field Awareness',
    'Drag Flick Mastery',
    'Tackling Techniques',
    'Seated Stick Control (Para)',
    'Visually Assisted Drills (Para)',
  ],
  Judo: [
    'Throwing Techniques',
    'Defensive Holds',
    'Mat Control',
    'Grip Fighting',
    'Transitioning Techniques',
    'Blind Grip Response (Para)',
    'Tactile Balance Training (Para)',
  ],
  Rowing: [
    'Timing Sync',
    'Stroke Efficiency',
    'Water Drills',
    'Feathering Techniques',
    'Team Synchronization',
    'Fixed Seat Stroke Form (Para)',
    'Arm-Only Rowing Training (Para)',
  ],
  Shooting: [
    'Aim Control',
    'Steady Breathing',
    'Trigger Discipline',
    'Target Transition Speed',
    'Scoring Consistency',
    'Adaptive Trigger Use (Para)',
    'Balance Support Techniques (Para)',
  ],
  Squash: [
    'Court Movement',
    'Shot Control',
    'Spin Strategy',
    'Wall Bounce Prediction',
    'Boast Shot Accuracy',
    'Seated Racket Range (Para)',
    'Non-Dominant Hand Play (Para)',
  ],
  Swimming: [
    'Breathing Techniques',
    'Freestyle Perfection',
    'Butterfly Stroke',
    'Turn Efficiency',
    'Streamline Starts',
    'One-Arm Stroke Optimization (Para)',
    'Leg Buoyancy Drills (Para)',
  ],
  'Table Tennis': [
    'Spin Serves',
    'Smash Return',
    'Quick Reflex',
    'Backhand Push',
    'Topspin Looping',
    'Wheelchair Court Reach (Para)',
    'Single-Handed Grip Styles (Para)',
  ],
  Taekwondo: [
    'Kick Accuracy',
    'Defense & Blocks',
    'Poomsae',
    'Counter Kick Timing',
    'Sparring Mindset',
    'Balance with Lower Limb Loss (Para)',
    'Adaptive Pad Striking (Para)',
  ],
  Tennis: [
    'Backhand Training',
    'Serve Precision',
    'Net Play',
    'Topspin Control',
    'Footwork Transition',
    'Wheelchair Movement Drills (Para)',
    'Low Bounce Reaction Practice (Para)',
  ],
  Volleyball: [
    'Spiking',
    'Blocking',
    'Serving Techniques',
    'Digging Fundamentals',
    'Rotation Communication',
    'Seated Attack Training (Para)',
    'Arm Swing Without Jump (Para)',
  ],
  'Weight Lifting': [
    'Deadlift Form',
    'Snatch Techniques',
    'Strength Building',
    'Grip Variants',
    'Overhead Stability',
    'Seated Lifting Mechanics (Para)',
    'Core Support Isolation (Para)',
  ],
  Wrestling: [
    'Grappling',
    'Takedown Strategy',
    'Mat Control',
    'Pinning Combos',
    'Counter-Wrestling',
    'One-Limb Leverage Drills (Para)',
    'Mat Entry & Exit Techniques (Para)',
  ],
};
